version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
          timezone: 'Europe/Rome'
      commit-message:
          prefix: 'ci'
          include: 'scope'
