aliases:
    - &job-defaults
      working_directory: ~/semaphore
      docker:
          - image: circleci/node:17.2.0

    - &yarn-install
      run:
          name: Running Yarn install
          command: yarn install --frozen-lockfile --non-interactive

    - &restore-cache
      name: Restore Yarn Package Cache
      keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # Fallback in case checksum fails
          - yarn-packages-{{ .Branch }}-

    - &save-cache
      name: Save Yarn Package Cache
      paths:
          - node_modules
      key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

    - &release_branches_filter
      branches:
          only:
              - master
              - /rc-.*/

    - &attach-workspace
      attach_workspace:
          at: ~/

version: 2.1
jobs:
    setup:
        <<: *job-defaults
        steps:
            - checkout
            - restore_cache: *restore-cache
            - *yarn-install
            - save_cache: *save-cache
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - ./semaphore

    lint:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  name: Lint
                  command: yarn lint:ci
            - run:
                  name: Lint Commits
                  command: yarn commitlint-circle
            - store_test_results:
                  path: reports

    test:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn test:ci
            - store_test_results:
                  path: reports

    check-dependencies:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn check-dependencies

    check-format:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn check-formatting

    doc:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn doc
            - store_artifacts:
                  path: docs

    build:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn build
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - ./semaphore/dist

    release:
        <<: *job-defaults
        steps:
            - *attach-workspace
            - run:
                  command: yarn semantic-release

workflows:
    version: 2
    default_workflow:
        jobs:
            - setup
            - lint:
                  requires:
                      - setup
            - test:
                  requires:
                      - setup
            - doc:
                  requires:
                      - setup
            - build:
                  requires:
                      - setup
            - check-format:
                  requires:
                      - setup
            - check-dependencies:
                  requires:
                      - build
            - release:
                  filters: *release_branches_filter
                  requires:
                      - lint
                      - test
                      - doc
                      - build
                      - check-dependencies
